/**
 ** This file is part of the ImgConv project.
 ** Copyright 2022-2023 Grégoire BOST <bostgregoire@gmail.com>.
 **
 ** This program is free software: you can redistribute it and/or modify
 ** it under the terms of the GNU Lesser General Public License as
 ** published by the Free Software Foundation, either version 3 of the
 ** License, or (at your option) any later version.
 **
 ** This program is distributed in the hope that it will be useful,
 ** but WITHOUT ANY WARRANTY; without even the implied warranty of
 ** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 ** GNU Lesser General Public License for more details.
 **
 ** You should have received a copy of the GNU Lesser General Public License
 ** along with this program.  If not, see <http://www.gnu.org/licenses/>.
 **/

#include "sobel.h"

ConvKernels::Sobel::Sobel(QObject *parent)
    : ConvKernel{parent} {
    setSourceFilePath(":/ocl/sobel.cl");
}

QVector<QVector<float> > ConvKernels::Sobel::getMat() const {
    static QVector<QVector<float>> k = {
        {0, 0, 0},
        {0, 0, 0},
        {0, 0, 0}
    };

    return k;
}

float ConvKernels::Sobel::getScalar() const {
    return 1.f;
}

QString ConvKernels::Sobel::getName() const {
    return tr("Sobel");
}

QString ConvKernels::Sobel::getDescription() {
    return tr("Applies an <i>Sobel</i> effect (a kind of edge-detection effect).<br><br>" \
              "This effect doesn't have any parameters to tweak.<br><br>" \
              "<strong>Note :</strong>The convolution matrices are harcoded in <i>:/ocl/sobel.cl</i> " \
              "The matrix generated by this effect is not used by the program.");
}
